### ISSUE TITLE
the private key loaded in will disappear when refreshing the page

### ISSUE THREAD

**Issue by maxlyrical** [pintswap/pintswap-app#137]
![image](https://github.com/pintswap/pintswap-app/assets/131549902/e961faa7-224a-42b7-a410-4ebdd7fbd04d)

**Comment by yoyobojo** [comment]
This is the expected result because we do not want to store the private key in the peer object. A good solution for this is to add an "info" icon that opens a tooltip describing that "this key will be removed after leaving the page"
